### ISSUE TITLE
ES7 property initializers not highlighted properly

### ISSUE THREAD

**Issue by syvanpera** [neoclide/vim-jsx-improve#10]
Looks like something breaks the highlight for property initializers. The first one is colored correctly, but the second one is not (see screenshot).

![screen shot 2017-06-27 at 13 27 11](https://user-images.githubusercontent.com/281128/27583230-5b8e612a-5b3c-11e7-9757-a830644dace2.png)

**Comment by chemzqm** [comment]
fixed
