### ISSUE TITLE
Doesn't understand JSX within arrays

### ISSUE THREAD

**Issue by kasbah** [neoclide/vim-jsx-improve#12]
```jsx
function example() {
  return [<div />, <div />];
}
function example2() {
  return <div />;
}
```

![image](https://user-images.githubusercontent.com/206854/28679989-da82fd02-72ec-11e7-8154-8e77ce52cd91.png)

**Comment by chemzqm** [comment]
Fixed in c167c3e53fd0259ce23ea9e3331e1462f1519854
<img width="256" alt="screen shot 2017-08-15 at 12 16 25 pm" src="https://user-images.githubusercontent.com/251450/29302067-9dad4164-81b3-11e7-94c6-af0ce7553951.png">
