### ISSUE TITLE
Am I missing the point

### ISSUE THREAD

**Issue by chollier** [neoclide/vim-jsx-improve#15]
Hey,

I'm not sure to get what gets improved:

before:
<img width="918" alt="screenshot 2017-08-18 09 37 37" src="https://user-images.githubusercontent.com/1869/29468419-fdaa1b7c-83f8-11e7-808e-ad99a3906496.png">

after:
<img width="918" alt="screenshot 2017-08-18 09 37 25" src="https://user-images.githubusercontent.com/1869/29468423-040eae60-83f9-11e7-97d4-774ef7d4c32f.png">

**Comment by kasbah** [comment]
The main thing for me is auto-indenting which doesn't work with JSX using any of the other JS or JSX syntax packages. With vim-jsx-improve installed I am able to write badly indented stuff, select everything and press `=`.

**Comment by chollier** [comment]
Oh I see, I use prettier / neoformat so it doesn't really matter too much

**Comment by chemzqm** [comment]
@chollier looks like the highlight syntax you usefull have better default for you scheme, here is what used by vim-jsx-improve:
``` vim
  highlight def link jsxTagName Statement
  highlight def link jsxEndString Statement
  highlight def link jsxEqual Function
  highlight def link jsxTag Function
  highlight def link jsxEndTag Function
  highlight def link jsxAttrib Type
  highlight def link jsxAttributeBraces Special
```
you can override it by define a highlight in your `.vimrc`
