### ISSUE TITLE
How to enable in typscript `tsx` files

### ISSUE THREAD

**Issue by joshua7v** [neoclide/vim-jsx-improve#16]
indent correctly when filetype == javascript / javascript.jsx
indent not correctly when filetype == typescript / typescript.tsx

**Comment by chemzqm** [comment]
You could copy the content of `after/syntax/javascript.vim` to `~/.vim/after/syntax/typescript.vim`, it might works.

**Comment by dhilst** [comment]
I have to edit this line `if index(['javascript', 'javascript.jsx', 'typescript'], &ft) == -1 | finish | endif` adding the `'typescript'` otherwise it finishes
