### ISSUE TITLE
better to change set iskeyword to exclude .

### ISSUE THREAD

**Issue by noscripter** [neoclide/vim-jsx-improve#17]
```viml
set iskeyword-=.
```

This options is overridden which causes search to miss correct matches.

**Comment by chemzqm** [comment]
`.` is excluded by default and vim-jsx-improve would not override `iskeyword `, looks like you should check where you have include `.` to iskeyword

**Comment by noscripter** [comment]
Running: `:verbose set iskeyword?` returns follow result, so i suspect it's set from this plugin.

![image](https://user-images.githubusercontent.com/1673877/32823555-939b1392-ca18-11e7-9205-f8e37226e92c.png)

**Comment by chemzqm** [comment]
@noscripter vim-jsx-improve only add `$` like `vim-javascript` did,
you could disable `vim-jsx-improve` and run `:verbose set iskeyword?` again.
