### ISSUE TITLE
Curly Braces Highlighting Incorrect

### ISSUE THREAD

**Issue by j-halbert** [neoclide/vim-jsx-improve#28]
Once JSX is introduced to a file, the incorrect opening/closing curly brace is matched when the cursor is over one of the matching braces.  The more code that's in the file, the more unpredictable the highlighting seems to be.  For example, the following will mismatch the closing curly brace on the JSX tag, with all others working proper:

```
  function(props) {
    return (
      <MyComponent attrib={ noHighlightingCorrectly } />
    )
  }
```

**Comment by zhujinxuan** [comment]
I have the same problem:
![](http://g.recordit.co/S963kljiaN.gif)
The following is

**Comment by chemzqm** [comment]
Looks like it's issue with matchparen.vim see https://github.com/mxw/vim-jsx/issues/146

**Comment by j-halbert** [comment]
@chemzqm I'm not using matchparen.vim.  And the referenced issue points out that, even using an alternative to matchparen, the problem still exists.

**Comment by chemzqm** [comment]
matchparen.vim is a built in plugin of vim/neovim.
@j-halbert I found remove the match for braces in jsx tags could resolve this problem.

**Comment by j-halbert** [comment]
@chemzqm thanks for the clarification.  The above commit fixes the issue on my machine. :+1:
