### ISSUE TITLE
Strange highlighting in html files after script tag

### ISSUE THREAD

**Issue by KabbAmine** [neoclide/vim-jsx-improve#29]
I'm not sure if the culprit is vim-jsx-improve or [html5.vim](https://github.com/othree/html5.vim), but the html highlighting is messed up after a `<script>` tag, see https://github.com/othree/html5.vim/issues/94.

**UPDATE**

Its definitely vim-jsx-improve, I have the same issue with the built-in html vim syntax.

**Comment by chemzqm** [comment]
I'm using html5.vim as well, but didn't get your problem.
Try use command:
```
echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '>'
```
under the unexpected highlight text and paste your result here.

**Comment by chemzqm** [comment]
@KabbAmine it's not problem of lazy loading, in https://github.com/kchmck/vim-coffee-script file `after/syntax/html.vim` it's including `syn include @htmlCoffeeScript syntax/coffee.vim` and in `syntax/coffee.vim` it has `syn include @coffeeJS syntax/javascript.vim`

**Comment by KabbAmine** [comment]
@chemzqm Thanks for your input.

I know for the inclusions, but there are no highlighting issues with vim-coffee-script and vim-javascript (pangloss) when used together, the problem occurs only when adding vim-jsx-improve.

What do you advice?

**Comment by KabbAmine** [comment]
:+1:
