### ISSUE TITLE
Javascript inside a JSX tag not highlighted

### ISSUE THREAD

**Issue by phreax** [neoclide/vim-jsx-improve#3]
Thanks for the wonderful plugin!

One thing I noticed though, is that javascript as content of a JSX tag seems not
to be highlighted. See line 20:

![image](https://cloud.githubusercontent.com/assets/85244/23263256/fcea0468-f9dd-11e6-8c7b-8e3504644af6.png)

**Comment by chemzqm** [comment]
![screen shot](https://cloud.githubusercontent.com/assets/251450/23265945/4e1e1cfa-fa21-11e6-866d-ec49956e606f.jpeg)
The highlight works fine on my machine, it could possibly cause by plugin conflict.

**Comment by phreax** [comment]
Hi, thanks for the reply!

No, I removed all JSX and Javascript related plugins (hopefully). Do you have any other plugins?
From the syntax file I cannot see how it may possibly work, but I might be wrong.
Anyway, I created a PR to fix it on my side.

**Comment by phreax** [comment]
Oh, sorry I just saw that I had the vim-es6 plugin installed, which seems to be responsible for that.
Without it works even without my fix.
