### ISSUE TITLE
Object properties highlighted differently in JSX context

### ISSUE THREAD

**Issue by kirjavascript** [neoclide/vim-jsx-improve#30]
![buggo](http://i.imgur.com/wEhkzcX.png)

this doesn't appear to happen with vim-javascript + vim-jsx, and I can't imagine it's a colourscheme thing. (I'm using onedark.vim for reference)

**Comment by chemzqm** [comment]
Fixed, thanks for reporting.

**Comment by chemzqm** [comment]
Oh, I made a mistake.

**Comment by chemzqm** [comment]
It could be fixed, but the fix would cause other highlight and indent issues, I will left this issue open for now.
