### ISSUE TITLE
coexist with vim-javascript config?

### ISSUE THREAD

**Issue by L-Jovi** [neoclide/vim-jsx-improve#32]
I already removed vim-javascript plugin while replace with your smart vim-jsx-improve, but I want to reserve some config from vim-javascript like below.

```
    let g:javascript_plugin_ngdoc = 1
    let g:javascript_plugin_flow = 1

    set foldmethod=syntax
    augroup javascript_folding
        au!
        au FileType javascript setlocal foldmethod=syntax
    augroup END

    let g:javascript_conceal_function             = "ƒ"
    let g:javascript_conceal_null                 = "ø"
    let g:javascript_conceal_this                 = "@"
    let g:javascript_conceal_return               = "⇚"
    let g:javascript_conceal_undefined            = "¿"
    let g:javascript_conceal_NaN                  = "ℕ"
    let g:javascript_conceal_prototype            = "¶"
    let g:javascript_conceal_static               = "•"
    let g:javascript_conceal_super                = "Ω"
    let g:javascript_conceal_arrow_function       = "⇒"
    let g:javascript_conceal_noarg_arrow_function = "🞅"
    let g:javascript_conceal_underscore_arrow_function = "🞅"
    set conceallevel=1
```

Most of items work well, but I find some issue after arrow function within tag, notice below image `"?"
` symbol, some code be hidden unless cursor move on that line, how should I fix it?

__strange ? symbol__
![image](https://user-images.githubusercontent.com/7262199/42856345-6b00f620-8a77-11e8-8be3-69ee7c741bd7.png)

__hidden code after arrow function__

![image](https://user-images.githubusercontent.com/7262199/42856643-a982972c-8a78-11e8-9579-fee943cc8f56.png)

Thanks for your time :)

regards.

**Comment by chemzqm** [comment]
Looks like it's issue of your font, does:
``` vim
   let g:javascript_conceal_noarg_arrow_function = "🞅"
   let g:javascript_conceal_underscore_arrow_function = "🞅"
```
Looks right in your vim file? I can't debug it since you're using custom unicode character which I don't have.

**Comment by L-Jovi** [comment]
@chemzqm Thanks for your quickly reply :)

I snapshot my vimrc like below

![image](https://user-images.githubusercontent.com/7262199/42856740-2873922a-8a79-11e8-9ef6-b4f9c3a04fd0.png)

Maybe github cannot display font normally >_<

**Comment by chemzqm** [comment]
The font using by vim not supporting the character you need, I think you need to install the font according to the documentation of vim-javascript and make your terminal use it.

**Comment by L-Jovi** [comment]
Thanks, I get it :)
