### ISSUE TITLE
Incorrect highlighting of an object literal in a prop

### ISSUE THREAD

**Issue by osenvosem** [neoclide/vim-jsx-improve#33]
![1](https://user-images.githubusercontent.com/6762673/43259947-a02db954-90e0-11e8-8819-2a50aa8f90fd.png)

**Comment by chemzqm** [comment]
Most likely you're using plugin `pangloss/vim-javascript` with `vim-jsx-improve`, disable `vim-javascript` to resolve this issue.

**Comment by osenvosem** [comment]
@chemzqm yes, I am. Thank you.
Nice job with the plugin. =)
