### ISSUE TITLE
arrow functions with multiline args lose javascript syntax highlighting

### ISSUE THREAD

**Issue by redbmk** [neoclide/vim-jsx-improve#36]
Sorry to keep raising so many issues, I'm just posting them as I run into them. When using arrow functions that have the arguments split into multiple lines, syntax highlighting breaks inside the function:

```
function normalFunction({ arg1, arg2 }) {
  const asdf = 'zxcv';
  return asdf;
}

function normalFunctionMultiline({
  arg1,
  arg2,
}) {
  const asdf = 'zxcv';
  return asdf;
}

const arrowFunction = ({ arg1, arg2 }) => {
  const asdf = 'zxcv';
  return asdf;
};

const arrowFunctionMultiline = ({
  arg1,
  arg2,
}) => {
  const asdf = 'zxcv';
  return asdf;
};
```
The colors look fine for the first three functions, but the last one looks off:

![broken highlighting](https://user-images.githubusercontent.com/83964/43481422-c405a1c4-94ba-11e8-8dcf-cacb3ecdaa59.png)

**Comment by chemzqm** [comment]
Fixed by 7c4c885
