### ISSUE TITLE
Not working with Fragment shorthand

### ISSUE THREAD

**Issue by redbmk** [neoclide/vim-jsx-improve#40]
When using React's [short Fragment syntax](https://reactjs.org/docs/fragments.html#short-syntax) (`<>`/`</>`), some styling breaks. It seems fine unless you put something in a `{}` block without being wrapped in a jsx element.

```
import React, { Fragment } from "react";

export const ThisWorks = () => (
  <>
    <div>
      <span>Hello</span>
    </div>
  </>
);

export const SoDoesThis = ({ someProps }) => (
  <>
    <div>
      <span>Hello</span>
    </div>
    <div>
      <span>World</span>
    </div>
  </>
);

export const ThisDoesNot = ({ shouldSayHi }) => (
  <>
    {shouldSayHi && (
      <div>
        <span>Hello</span>
      </div>
    )}
    <div>
      <span>World</span>
    </div>
  </>
);

export const ButThisDoes = ({ shouldSayHi }) => (
  <Fragment>
    {shouldSayHi && (
      <div>
        <span>Hello</span>
      </div>
    )}
    <div>
      <span>World</span>
    </div>
  </Fragment>
);
```

**Comment by chemzqm** [comment]
Yep, it's not supported yet.

**Comment by redbmk** [comment]
You rock! ❤️

**Comment by redbmk** [comment]
@chemzqm This latest change fixed the fragment shorthand, but actually broke some basic javascript comparison syntax 😱 :

## before
![image](https://user-images.githubusercontent.com/83964/45315511-75b55d80-b4e9-11e8-9b2b-747d9c2b52c1.png)


## after
![image](https://user-images.githubusercontent.com/83964/45315428-4141a180-b4e9-11e8-9fbb-328073fa9233.png)

**Comment by chemzqm** [comment]
Fixed

**Comment by redbmk** [comment]
Awesome, thanks! Looks great!
