### ISSUE TITLE
Syntax/indent failure on nested {code block}

### ISSUE THREAD

**Issue by JESii** [neoclide/vim-jsx-improve#45]
First off,  -- thanks for fixing the problems with the old `vim-jsx` plugin. The issues there were driving me crazy!

With a complex {...} code block in a component, syntax highlighting breaks down and leads to indent failures. Here's an annotated screenshot, followed by the code itself. This is implementing Google's Material-UI Popper, using their recommended code for the TransitionProps.
![image](https://user-images.githubusercontent.com/486/56583858-645c2580-658f-11e9-84d7-3e2c4120a84b.png)
```
  renderPopper(dateIndex, templateIndex) {
    const { anchorEl, open } = this.state;
    const id = open ? 'simple-popper' : null;
    <Popper id={id} open={open} variant="contained" placement="bottom-emd" anchorEl={anchorEl} transition>
      {({ TransitionProps }) => (
        <Fade {...TransitionProps} timeout={350}>
          <Paper>
            <Typography variant="contained" style={{border: '2px' }} className={classes.popper}>
              {this.renderScheduleItem(dateIndex, templateIndex)}
            </Typography>
          </Paper>
        </Fade>
    )}
  </Popper>
  };
```
And yes, I no longer have `vim-javascript` installed.

**Comment by chemzqm** [comment]
Can't reproduce, highlight and indent work as expected for me, please test it by minimal vimrc.
