### ISSUE TITLE
是否有必要添加新的说明在Readme

### ISSUE THREAD

**Issue by taigacute** [neoclide/vim-jsx-improve#49]
`jsxEndComponentName`是其他插件没有的一个高亮组，是否有必要将jsx的高亮组添加到Readme中？只有我个主题[gruvbox9](https://github.com/taigacute/gruvbox9)现在是支持的可以和vim-jsx-improve完美使用。

**Comment by chemzqm** [comment]
加一个默认的 link。

**Comment by taigacute** [comment]
Ok
