### ISSUE TITLE
Syntax Folding lacking compared to vim javascript

### ISSUE THREAD

**Issue by sbussetti** [neoclide/vim-jsx-improve#5]
![image](https://cloud.githubusercontent.com/assets/913361/24960207/18011516-1f63-11e7-91f0-42ce4750ec6e.png)

I've got vim-jsx, vim-jsx-improve installed.  The above is using foldmethod=syntax.

The indent support in vim-javascript is abysmal for es6 / jsx, so I switched to yours, which is a little less aggressive than I'd like but also doesn't completely destroy my existing indents like vim-javascript does, so that's pretty cool.  However, since your and vim-javascript are not compatible, I lose vim-javascripts superior code folding support.  

Let me know what additional info I can provide, how I could help test etc.

**Comment by chemzqm** [comment]
Hm, I removed most of fold definition intentionally but keep the fold for function only, you can add `fold` keyword to the definition you want by yourself, ex: https://github.com/neoclide/vim-jsx-improve/blob/master/syntax/javascript.vim#L146

**Comment by chemzqm** [comment]
The fold was removed for perfomancee reason, sorry for the unconvinence.
