### ISSUE TITLE
Syntax highlighting does not work in some places after updating vim-jsx-improve to latest.

### ISSUE THREAD

**Issue by Bikashd4332** [neoclide/vim-jsx-improve#53]
![image](https://user-images.githubusercontent.com/23401383/86427319-890d6a80-bd07-11ea-8c37-8735c6e5013e.png)
As you can see above at the BackdropProps it highlights it as an error.

![image](https://user-images.githubusercontent.com/23401383/86427538-0df88400-bd08-11ea-8f31-b115b6b50f4d.png)
Although, my coc says `Empty diagnostic`.

**Comment by chemzqm** [comment]
You have to make sure you have filetype `javascript.jsx` or `javascriptreact`
