### ISSUE TITLE
Highlight text in between tags as strings?

### ISSUE THREAD

**Issue by kasbah** [neoclide/vim-jsx-improve#9]
It would be nice if text in between tags were highlighted like strings. So instead of:

![image](https://user-images.githubusercontent.com/206854/27203343-56e30d2e-521d-11e7-9dee-1fb3191b026b.png)

we had:

![image](https://user-images.githubusercontent.com/206854/27203422-b3898904-521d-11e7-9e78-9be21cc327dc.png)

**Comment by chemzqm** [comment]
I personally think that's not a good idea, however, you can do that by:
```
hi link jsxRegion string
```

**Comment by kasbah** [comment]
Hey, first off thanks for creating this and addressing the other issues I created!

Why do you think it's a bad idea? I find it confusing that HTML text is highlighted the same as JS code. 
I find the second one much easier to read.

![image](https://user-images.githubusercontent.com/206854/27213526-59e84b8c-525f-11e7-806e-f0c9b0f51327.png)
![image](https://user-images.githubusercontent.com/206854/27213530-5e1befe2-525f-11e7-9c21-a0d31fd82e11.png)

`hi link jsxRegion string` does seem to work unless there is a comma in the text.

**Comment by chemzqm** [comment]
I agree, but xml & html highlight would not highlight their content as string, so I think that would be confusing to do that for jsx.
We can fix the comma problem.

**Comment by kasbah** [comment]
How would you fix the comma problem?

**Comment by chemzqm** [comment]
I have rewrite to syntax rules in c167c3e the comma no longer a problem now.

**Comment by kasbah** [comment]
Thanks very much for improving vim-jsx-improve! To spell it out for those wanting to highlight text within tags as strings, like me, you can add this to your .vimrc:

```
au BufRead,BufNewFile *.js,*.jsx hi link jsxRegion string
```
